### PR TITLE
Fix builtin template "all-plugins" being deselected by accident

### LINKED ISSUE #49: Default Template breaks "Show All Plugins" Template
When a default template is set via the settings (e.g. `DEFAULT_UI_TEMPLATE = 2`) the `show all plugins` template doesn't work. When the user selects the `show all plugins` template and clicks on a plugin in the sidebar the UI switches to the default template.

This is probably due to the `templateId` being `null` when the `selectPlugin` method is called (more specifically in line 376).

https://github.com/UST-QuAntiL/qhana-ui/blob/9d20d8e165dd212c4058953bcf25484ab54468cd/src/app/components/plugin-sidebar/plugin-sidebar.component.ts#L369-L380

For the `show all plugins` template to work the URL parameter must remain `template=all-plugins`.

### PR DESCRIPTION
**Pull request by buehlefs**
Fixes #49

Navigation to plugins and tabs only used the internal `templateId` and ignored the new flag for the builtin default plugins template. Solved by introducing an `effectiveTemplateId` getter for navigation.

I have not tested the fix locally, but I am pretty sure it should work... (do not merge without actually testing the fix)

### CODE REVIEW

File: src/app/components/plugin-sidebar/plugin-sidebar.component.ts [hunk 1]
```diff
@@ -57,15 +60,22 @@ export class PluginSidebarComponent implements OnInit, OnDestroy {
     private deletedTabSubscription: Subscription | null = null;
     private changedTemplateSubscription: Subscription | null = null;
 
+    get effectiveTemplateId(): string | null {
+        if (this.useDefaultTemplate) {
```
Comment (infacc) [inline src/app/components/plugin-sidebar/plugin-sidebar.component.ts:64]: It seems to me that inverting this condition achieves the desired behavior.

```suggestion
        if (!this.useDefaultTemplate) {
```

Currently, selecting a plugin in the `all-plugins` template switches to the default template (`DEFAULT_UI_TEMPLATE`), and selecting a plugin in another template switches to the `all-plugins` template.

**Review by infacc — CHANGES_REQUESTED** [review]

File: src/app/components/plugin-sidebar/plugin-sidebar.component.ts (hunk 1 above)
Comment (buehlefs) [reply src/app/components/plugin-sidebar/plugin-sidebar.component.ts]: Should be fixed now. And this time I have also tested it locally.

**Comment by infacc** [comment]
Without the `template` URL parameter, the plugin sidebar didn't get populated in the `details` view. The same problem occurred in the experiment-workspace-detail. The mat-accordions stayed empty.

It works now. However, I'm not sure if using a subscription is the best approach (for the experiment-workspace-detail component):
https://github.com/UST-QuAntiL/qhana-ui/blob/dcba177d6cc391861653c07fc4327abbe5ba04cc/src/app/components/experiment-workspace-detail/experiment-workspace-detail.component.ts#L196-L202

File: src/app/components/plugin-sidebar/plugin-sidebar.component.ts [hunk 2]
```diff
@@ -66,7 +66,8 @@ export class PluginSidebarComponent implements OnInit, OnDestroy {
             // and external default templates should not be used
             return this.templateId ?? ALL_PLUGINS_TEMPLATE_ID;
         }
-        return this.templateId;
+        const defaultTemplateId = this.defaultTemplate?.self?.resourceKey?.uiTemplateId ?? null
```
Comment (buehlefs) [inline src/app/components/plugin-sidebar/plugin-sidebar.component.ts:69]: This will cause the template id to be written to the url upon navigation, which will prevent changes to the default template to apply. This is not the correct fix to this problem (and I need to replicate the problem myself to see where the issue is)

**Review by buehlefs — COMMENTED** [review]
Looks like I need to investigate this issue further...

**Review by infacc — APPROVED** [review]
